// Generated by CodiumAI
import { TABLE_TYPE } from '@/config/tables'
import { renderWithProviders } from '@/helpers/jest-react'
import { screen } from '@testing-library/react'

import Table from './ProTable'

describe('Table', () => {
  // Renders a table with the correct columns and data
  it('should render a table with the expected columns and data', async () => {
    // Arrange
    const rowData = [
      { id: '1', height: 100, canonical: true, tipset_timestamp: '2022-01-01T00:00:00Z', 'blocks_info-1': 'Block1' },
      { id: '2', height: 200, canonical: false, tipset_timestamp: '2022-01-02T00:00:00Z', 'blocks_info-1': 'Block2' },
      { id: '3', height: 300, canonical: true, tipset_timestamp: '2022-01-03T00:00:00Z', 'blocks_info-1': 'Block3' },
    ]

    // Act
    await renderWithProviders(
      <Table rowData={rowData} tableType={TABLE_TYPE.TIPSETS} treeData={false} noRowsPosition={'center'} mode={'normal'} />
    )

    // Assert
    expect(screen.getByRole('grid')).toBeInTheDocument()
    expect(screen.getByText('100')).toBeInTheDocument()
    expect(screen.getByText('200')).toBeInTheDocument()
    expect(screen.getByText('300')).toBeInTheDocument()
  })
})
