name: Lighthouse
on:
  push:
    branches:
      - main
      - master
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  lighthouseci:
    name: Lighthouse metrics
    runs-on: zondax-runners
    container:
      image: node:18-bookworm
      env:
        PROJECT: web-beryx
        NAMESPACE: web-beryx
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        HEAD_BRANCH_NAME: ${{ github.head_ref }}
        GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
        GHOST_API_KEY: ${{ secrets.GHOST_API_KEY }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        TURBO_TEAM: zondax
        NEXT_PUBLIC_NAT_SERVER_CREDENTIAL: ${{ secrets.NEXT_PUBLIC_NAT_SERVER_CREDENTIAL }}
        NEXT_PUBLIC_NAT_SERVER: ${{ secrets.NEXT_PUBLIC_NAT_SERVER }}
        NEXT_PUBLIC_MUI_GRID_LICENSE: ${{ secrets.NEXT_PUBLIC_MUI_GRID_LICENSE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # Perform a deep clone (fetch all history)
          submodules: 'recursive' # Fetch Git submodules recursively

          # Related to https://github.com/actions/runner/issues/2033
      - name: Patch git clone
        run: git config --system --add safe.directory '*'

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: npx turbo build

      - name: Install Chrome Browser
        run: npx playwright install chrome

      - run: yarn lhci collect

      - run: yarn lhci upload
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
