name: 'Playwright tests'
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

env:
  PROJECT: web-beryx
  NAMESPACE: web-beryx
  HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  HEAD_BRANCH_NAME: ${{ github.head_ref }}

jobs:
  smoke:
    name: Playwright Smoke
    runs-on: zondax-runners
    container:
      image: node:18-bookworm
      env:
        GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
        GHOST_API_KEY: ${{ secrets.GHOST_API_KEY }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        NEXT_PUBLIC_NAT_SERVER_CREDENTIAL: ${{ secrets.NEXT_PUBLIC_NAT_SERVER_CREDENTIAL }}
        NEXT_PUBLIC_NAT_SERVER: ${{ secrets.NEXT_PUBLIC_NAT_SERVER }}
        NEXT_PUBLIC_MUI_GRID_LICENSE: ${{ secrets.NEXT_PUBLIC_MUI_GRID_LICENSE }}
        TURBO_TEAM: zondax
        CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Disable shallow clone
      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: npx turbo build

      - name: Install dependencies
        run: yarn e2e:install

      - name: Run Playwright tests
        run: yarn e2e:smoke
        env:
          CLOUDFLARE_PROTECTED_API_CLIENT_ID: ${{ secrets.CLOUDFLARE_PROTECTED_API_CLIENT_ID }}
          CLOUDFLARE_PROTECTED_API_CLIENT_SECRET: ${{ secrets.CLOUDFLARE_PROTECTED_API_CLIENT_SECRET }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 15
